"""esquema base

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 20:36:33.516952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurso',
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('recurso_nombre', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('es_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('debe_cambiar_password', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('length(trim(recurso_nombre)) > 0', name='recurso_nombre_no_vacio'),
    sa.PrimaryKeyConstraint('recurso_id')
    )
    op.create_index('recurso_nombre_unico', 'recurso', [sa.literal_column('lower(recurso_nombre)')], unique=True)
    op.create_table('rol',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('rol_descripcion', sa.Text(), nullable=False),
    sa.CheckConstraint('length(trim(rol_descripcion)) > 0', name='rol_descripcion_no_vacia'),
    sa.PrimaryKeyConstraint('rol_id')
    )
    op.create_index('rol_descripcion_unica', 'rol', [sa.literal_column('lower(rol_descripcion)')], unique=True)
    op.create_table('proyecto',
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('proyecto_nombre', sa.Text(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('horas_requeridas', sa.Double(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('proyect_status', sa.Text(), nullable=False),
    sa.Column('porcentaje_avance', sa.Double(), server_default='0', nullable=False),
    sa.CheckConstraint("proyect_status IN ('pendiente','en curso','pausado','finalizado')", name='proyecto_estado'),
    sa.CheckConstraint('fecha_fin >= fecha_inicio', name='proyecto_fechas'),
    sa.CheckConstraint('horas_requeridas > 0', name='proyecto_horas_positivas'),
    sa.CheckConstraint('length(trim(proyecto_nombre)) > 0', name='proyecto_nombre_no_vacio'),
    sa.CheckConstraint('porcentaje_avance BETWEEN 0 AND 100', name='proyecto_avance'),
    sa.ForeignKeyConstraint(['owner_id'], ['recurso.recurso_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('proyecto_id')
    )
    op.create_index(op.f('ix_proyecto_owner_id'), 'proyecto', ['owner_id'], unique=False)
    op.create_table('sesion',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=True),
    sa.Column('csrf', sa.Text(), nullable=False),
    sa.Column('creada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recurso_id'], ['recurso.recurso_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_sesion_expira'), 'sesion', ['expira'], unique=False)
    op.create_index(op.f('ix_sesion_recurso_id'), 'sesion', ['recurso_id'], unique=False)
    op.create_table('consumo',
    sa.Column('consumo_id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('horas_consumidas', sa.Double(), nullable=False),
    sa.Column('tarea', sa.Text(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('fecha_fin >= fecha_inicio', name='consumo_fechas'),
    sa.CheckConstraint('horas_consumidas > 0', name='consumo_horas_positivas'),
    sa.CheckConstraint('length(trim(tarea)) > 0', name='consumo_tarea_no_vacia'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyecto.proyecto_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recurso_id'], ['recurso.recurso_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.rol_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('consumo_id')
    )
    op.create_index(op.f('ix_consumo_proyecto_id'), 'consumo', ['proyecto_id'], unique=False)
    op.create_index(op.f('ix_consumo_recurso_id'), 'consumo', ['recurso_id'], unique=False)
    op.create_index(op.f('ix_consumo_rol_id'), 'consumo', ['rol_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumo_rol_id'), table_name='consumo')
    op.drop_index(op.f('ix_consumo_recurso_id'), table_name='consumo')
    op.drop_index(op.f('ix_consumo_proyecto_id'), table_name='consumo')
    op.drop_table('consumo')
    op.drop_index(op.f('ix_sesion_recurso_id'), table_name='sesion')
    op.drop_index(op.f('ix_sesion_expira'), table_name='sesion')
    op.drop_table('sesion')
    op.drop_index(op.f('ix_proyecto_owner_id'), table_name='proyecto')
    op.drop_table('proyecto')
    op.drop_index('rol_descripcion_unica', table_name='rol')
    op.drop_table('rol')
    op.drop_index('recurso_nombre_unico', table_name='recurso')
    op.drop_table('recurso')
    # ### end Alembic commands ###
